### ISSUE TITLE
[FEATURE] Publish JDBC driver to Maven

### ISSUE THREAD

**Issue by kartg** [opensearch-project/sql-jdbc#24]
**Is your feature request related to a problem?**
At ApacheCon 2022, we spoke with folks from [DBeaver](https://github.com/dbeaver/dbeaver), who noted that their customers wanted integration with OpenSearch (https://github.com/dbeaver/dbeaver/issues/17811). DBeaver depends on JDBC drivers, and their preferred method of consuming the package is from Maven. 

**What solution would you like?**
Publish [the JDBC driver](https://opensearch.org/docs/2.3/search-plugins/sql/sql/jdbc/) to Maven.

**Comment by GumpacG** [comment]
Closing as the JDBC driver is now on Maven.
