### ISSUE TITLE
Request to publish the repository to Maven

### ISSUE THREAD

**Issue by newUserForTesting** [opensearch-project/sql-jdbc#32]
**Is your feature request related to a problem? Please describe.**
All of our projects use Maven for dependency management and we would love if the OpenSearch project is published to maven. For example: This will enable us to use OpenSearch - JDBC in our projects.

**Describe the solution you'd like**
Publishing the library to Maven

**Comment by GumpacG** [comment]
Closing as the JDBC driver is now on Maven. Latest: https://repo1.maven.org/maven2/org/opensearch/driver/opensearch-sql-jdbc/1.4.0.0/

**Comment by newUserForTesting** [comment]
Thanks Guian!
