### ISSUE TITLE
Baseline MAINTAINERS, CODEOWNERS, and external collaborator permissions

### ISSUE THREAD

**Issue by dblock** [opensearch-project/sql-jdbc#57]
Follow https://github.com/opensearch-project/.github/issues/125 to baseline MAINTAINERS, CODEOWNERS, and external collaborator permissions.

Close this issue when:

1. [MAINTAINERS.md](MAINTAINERS.md) has the correct list of project maintainers.
2. [CODEOWNERS](CODEOWNERS) exists and has the correct list of aliases.
3. Repo permissions only contain individual aliases as collaborators with maintain rights, admin, and triage teams. 
4. All other teams are removed from repo permissions.

If this repo's permissions was already baselined, please confirm the above when closing this issue.

**Comment by dblock** [comment]
You have the `sql` group with 18 members that has maintain access to this repo. Only folks listed in MAINTAINERS/CODEOWNERS need to have maintain access, and groups don't support external collaborators. Please work with an admin to remove the group and add individuals.

**Comment by dblock** [comment]
![Screenshot 2023-04-04 at 3 18 19 PM](https://user-images.githubusercontent.com/542335/229897559-73223000-ef75-4086-8d61-6e4dc50cba06.png)

**Comment by bbarani** [comment]
Added the users listed in MAINTAINERS.md file as maintainers of this repo. @anirudha @joshuali925 Please add CODEOWNERS file under .github directory with the maintainers list. CC: @dblock @CEHENKLE 

Also, I am not able to add [MaxKsyunz](https://github.com/MaxKsyunz) and [Yury-Fridlyand](https://github.com/Yury-Fridlyand) as they are not part of the organization yet. Please update the maintainers list as needed.

**Comment by derek-ho** [comment]
This is done, pending adding yury and max to github, which I have opened a ticket for

**Comment by dblock** [comment]
Verified, thx.
