### ISSUE TITLE
Appears that Struct is not a supported data type [BUG]

### ISSUE THREAD

**Issue by akuzin1** [opensearch-project/sql-jdbc#65]
**What is the bug?**
Attempted to extract Struct (by calling `resultSet.getObject(<fieldName>)`) on returned ResultSet from JDBC driver and received the following error `java.sql.SQLException: Conversion from OBJECT not supported.`

The following is what the mapping of my index looks like:

    "mappings": {
      "properties": {
        "details": {
          "properties": {
            "memory": {
              "type": "long"
            },
            "model": {
              "type": "text",
              "fields": {
                "keyword": {
                  "type": "keyword",
                  "ignore_above": 256
                }
              }
            }
          }
        },
        "item": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "price": {
          "properties": {
            "currency": {
              "type": "text",
              "fields": {
                "keyword": {
                  "type": "keyword",
                  "ignore_above": 256
                }
              }
            },
            "value": {
              "type": "long"
            }
          }
        }
      }
    }

Result set has the following columns:
1. Column 1 of type VARCHAR and name: item
2. Column 2 of type STRUCT and Name: details
3. Column 3 of type STRUCT and Name: price

**How can one reproduce the bug?**
1. Create an index with a struct or nested struct
2. Execute a query using the JDBC driver
3. Attempt to extract data from ResultSet by calling `resultSet.getObject(<fieldName>)` or `resultSet.getObject(<fieldName>, <xxx.class>)`
4. See error mentioned above

**What is the expected behavior?**
It is expected to be able to retrieve the struct data type from the current row of the ResultSet, the same way other data types can be accessed.

**What is your host/environment?**
 - OS: Lambda Function with Java 11 (Corretto) Runtime
 - Version: JDBC Driver version 1.2.0.0

**Comment by MaxKsyunz** [comment]
@akuzin1 thank you for submitting a ticket.

You are correct -- JDBC driver does not currently support `nested` and `object` OpenSearch data types.

**Comment by akuzin1** [comment]
#73
