### ISSUE TITLE
[FEATURE] Update 1-click release process to publish shadow jar as well

### ISSUE THREAD

**Issue by Yury-Fridlyand** [opensearch-project/sql-jdbc#98]
**Is your feature request related to a problem?**
Currently 1-click release process uploads artifacts to maven only. It should upload a signed shadow jar to artifact bucket as well.

**What solution would you like?**
Add uploading a signed shadow jar to artifact bucket as well.

**What alternatives have you considered?**
N/A

**Do you have any additional context?**
Refer to https://github.com/opensearch-project/opensearch-build/issues/3614 and https://github.com/opensearch-project/sql-odbc/pull/52

**Comment by acarbonetto** [comment]
waiting on https://github.com/opensearch-project/sql-jdbc/pull/106 to complete
